config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'conversations#index'

  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]
  resources :users, only: [:index]
  

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :author, class_name: 'User'
	belongs_to :receiver, class_name: 'User'
	has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

	validates :author, uniqueness: { scope: :receiver }

	scope :participating, -> (user) { where("(author_id = ? OR receiver_id = ?)", user.id, user.id) }
  scope :between, -> (sender_id, receiver_id) do
  	sql_clause = "author_id = sender_id AND receiver_id = receiver_id"
  	where("((author_id  = ? AND receiver_id = ?) OR (author_id = ? AND receiver_id = ?))",
  		    sender_id, receiver_id, receiver_id, sender_id).limit(1)
  end

  def with(current_user)
		author == current_user ? receiver : author
	end

	def participates?(user)
    author == user || receiver == user
	end

end

app/models/personal_message.rb
class PersonalMessage < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'receiver_id'
  has_many :personal_messages, dependent: :destroy


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  #validates :name, :last_name, :email, presence: true
  validate :full_name_must_be_unique

  def full_name
  	"#{name} #{last_name}"
  end

  private

  def full_name_must_be_unique
  	if new_record?
  		user = User.where(["name = ? AND last_name = ?", name, last_name])
  	else
  		user = User.where(["name = ? AND last_name = ? and id <> ?", name, last_name, id])
    end
  	errors.add(:full_name, "has already been taken") if user.present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

	before_action :set_conversation, except: [:index]
	before_action :check_participating!, except: [:index]

	def new
		redirect_to conversation_path(@conversation) and return if @conversation
		@personal_message = current_user.personal_messages.build
	end	

	def index
		@conversations = Conversation.participating(current_user).order('updated_at DESC')
	end

	def show
    @personal_message = PersonalMessage.new
	end

	private

	def set_conversation
		@conversation = Conversation.find_by(id: params[:id])
	end

	def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
	end

end

app/controllers/personal_messages_controller.rb
class PersonalMessagesController < ApplicationController
  before_action :find_conversation!

  def new
  	@personal_message = current_user.personal_messages.build
  end

  def create
  	@conversation ||= Conversation.create(author_id: current_user.id,
  		                                    receiver_id: @receiver.id)
  	@personal_message = current_user.personal_messages.build(personal_message_params)
  	@personal_message.conversation_id = @conversation.id
  	@personal_message.save!

  	flash[:success] = "Your message was sent!"
  	redirect_to conversation_path(@conversation)
  end

  private

  def personal_message_params
  	params.require(:personal_message).permit(:body)
  end
  
  def find_conversation!
    if params[:receiver_id]
      @receiver = User.find_by(id: params[:receiver_id])
      redirect_to(root_path) and return unless @receiver
      @conversation = Conversation.between(current_user.id, @receiver.id)[0]
    else
      @conversation = Conversation.find_by(id: params[:conversation_id])
      redirect_to(root_path) and return unless @conversation && @conversation.participates?(current_user)
    end
  end   	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/_conversation.html.haml
%div
  = "Chatting with #{conversation.with(current_user).name}"
  %br
  %em= conversation.personal_messages.last.body.truncate(50) 
  %br
  = link_to 'View conversation', conversation_path(conversation)
  %br

app/views/conversations/index.html.haml
%h1 Your conversations
#conversations
  - if @conversations
    = render @conversations
  - else
    =render plain: "No conversations yet."

app/views/conversations/show.html.haml
#conversation-main
  #conversation-body
    = render @conversation.personal_messages
  = form_for @personal_message do |f|
    = hidden_field_tag 'conversation_id', @conversation.id
    = f.label :body
    = f.text_area :body
    = f.submit
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title VanyaApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'shared/menu'
    = yield

app/views/personal_messages/_personal_message.html.haml
%p= personal_message.body
%p
  %strong= personal_message.created_at
  %br
  ="by #{personal_message.user.name}"
%hr

app/views/personal_messages/new.html.haml
%h1= "New message to #{@receiver.name}"
= form_for @personal_message do |f|
	= hidden_field_tag 'receiver_id', @receiver.id
	= f.label :body
	= f.text_area :body
	= f.submit
	

app/views/shared/_menu.html.haml
-flash.each do |key, value|
  .flash
    = value
-if user_signed_in?
  %p
    = "Signed in as #{current_user.name} | "
    = link_to 'log_out', destroy_user_session_path, method: :delete
%ul
  %li
    =link_to 'Home', root_path
    =link_to 'Users', users_path
    

app/views/users/_user.html.haml
%li
  = user.name + " | "
  = link_to 'send a message', new_personal_message_path(receiver_id: user)

app/views/users/index.html.haml
%h1 Users
%ul= render @users